FROM debian:9.5 as base

# https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
ARG TIME_ZONE

RUN mkdir /opt/etc && \
	cp /usr/share/zoneinfo/${TIME_ZONE:-ROC} /opt/etc/localtime

FROM gcr.io/distroless/base:debug

COPY --from=base /opt /opt

VOLUME /data
WORKDIR /opt

ENTRYPOINT [ "sh" ]